#!/usr/bin/env python3
"""Traces style B's picker silhouettes from the Linden body and writes core/src/picker_silhouette_data.inc.

    tools/picker_silhouette.py [build dir]      # default: build

Runs vats_picker_dump --silhouette (the chart pose on the SL default shape, carried into each page view's space by the
picker's own maths), fills each view's skin triangles into a mask, traces its outline (a slight blur first, so the
seams between mesh parts close), simplifies it and stores the loops with the chart bones they were traced around, in
0.1 mm units. Needs numpy, Pillow and contourpy (the picker mockups' tools).
"""
import json, os, subprocess, sys, tempfile

import numpy as np
from PIL import Image, ImageDraw, ImageFilter
import contourpy

VATS = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(VATS, 'core', 'src', 'picker_silhouette_data.inc')
RES = 1600           # mask pixels along a view's longer side
BLUR = 1.5           # mask pixels
TOLERANCE = 0.0018   # simplification, as a fraction of the view's size
UNIT = 1e-4          # stored units: 0.1 mm


def simplify(pts, tol):
    """Douglas-Peucker on an open polyline (numpy array)."""
    if len(pts) < 3:
        return pts
    a, b = pts[0], pts[-1]
    ab = b - a
    n = np.hypot(*ab)
    r = pts - a
    d = np.abs(ab[0] * r[:, 1] - ab[1] * r[:, 0]) / n if n > 0 else np.hypot(r[:, 0], r[:, 1])
    i = int(np.argmax(d))
    if d[i] <= tol:
        return np.array([a, b])
    return np.vstack([simplify(pts[:i + 1], tol)[:-1], simplify(pts[i:], tol)])


def trace(tris, cut=None):
    t = np.array(tris, float).reshape(-1, 3, 2)
    lo, hi = t.reshape(-1, 2).min(0), t.reshape(-1, 2).max(0)
    size = hi - lo
    margin = size.max() * 0.03
    lo, hi = lo - margin, hi + margin
    s = RES / (hi - lo).max()
    w, h = int((hi[0] - lo[0]) * s) + 1, int((hi[1] - lo[1]) * s) + 1
    img = Image.new('L', (w, h), 0)
    dr = ImageDraw.Draw(img)
    for tri in t:  # y up in page space, down in the mask
        dr.polygon([((x - lo[0]) * s, (hi[1] - y) * s) for x, y in tri], fill=255)
    if cut is not None:  # a straight end (the Face page's neck): nothing below the cut
        dr.rectangle([0, (hi[1] - cut) * s, w, h], fill=0)
    z = np.asarray(img.filter(ImageFilter.GaussianBlur(BLUR)), float) / 255
    loops = []
    for line in contourpy.contour_generator(z=z, line_type=contourpy.LineType.Separate).lines(0.5):
        pts = np.stack([line[:, 0] / s + lo[0], hi[1] - line[:, 1] / s], axis=1)
        area = 0.5 * abs(np.dot(pts[:-1, 0], pts[1:, 1]) - np.dot(pts[1:, 0], pts[:-1, 1]))
        if area < (size.max() * 0.02) ** 2:  # specks and holes
            continue
        if np.allclose(pts[0], pts[-1]):
            pts = pts[:-1]
        tol = TOLERANCE * size.max()
        # Split the closed loop at its farthest point from the start so both halves simplify well.
        k = int(np.argmax(np.hypot(*(pts - pts[0]).T)))
        half1, half2 = simplify(pts[:k + 1], tol), simplify(np.vstack([pts[k:], pts[:1]]), tol)
        loops.append(np.vstack([half1[:-1], half2[:-1]]))
    return loops


def main():
    build = sys.argv[1] if len(sys.argv) > 1 else os.path.join(VATS, 'build')
    dump = os.path.join(build, 'vats_picker_dump')
    with tempfile.TemporaryDirectory(dir=build) as tmp:
        js = os.path.join(tmp, 'silhouette.json')
        subprocess.run([dump, os.path.join(VATS, 'data', 'character'), js, '--silhouette'], check=True)
        views = json.load(open(js))['views']
    q = lambda v: str(int(round(v / UNIT)))
    out = ['// Viewport Avatar Toolset - style B\'s picker silhouettes. Generated by tools/picker_silhouette.py; do not edit.',
           '// Copyright (C) 2026 Viewport Avatar Toolset contributors. LGPL-2.1, see LICENSE.',
           '// Per page view: the chart bones the outline was traced around (ax, ay, bx, by) and its closed loops (x, y),',
           '// page space in 0.1 mm.']
    table, total = [], 0
    for v in views:
        tag = f"{v['page']}_{v['view']}"
        loops = trace(v['tris'], v.get('cut')) if v['tris'] else []
        names = ','.join(a[0] for a in v['anchors'])
        anchors = [q(x) for a in v['anchors'] for x in a[1:]]
        pts, ends = [], []
        for loop in loops:
            pts += [q(x) for p in loop for x in p]
            ends.append(str(len(pts) // 2))
        total += len(pts) // 2
        chunks = [names[i:i + 100] for i in range(0, len(names), 100)] or ['']
        out.append(f'const char kNames{tag}[] =\n' + '\n'.join(f'    "{c}"' for c in chunks) + ';')
        out.append(f'const short kAnchors{tag}[] = {{{", ".join(anchors) or "0, 0, 0, 0"}}};')
        out.append(f'const short kPoints{tag}[] = {{{", ".join(pts) or "0, 0"}}};')
        out.append(f'const unsigned short kLoops{tag}[] = {{{", ".join(ends) or "0"}}};')
        table.append(f'    {{{v["page"]}, {v["view"]}, kNames{tag}, kAnchors{tag}, {len(anchors)}, kPoints{tag}, kLoops{tag}, '
                     f'{len(ends)}}},')
    out.append('const SilView kSilViews[] = {')
    out += table
    out.append('};')
    text = '\n'.join(out) + '\n'
    # Wrap the long number lists at 120 columns.
    wrapped = []
    for line in text.split('\n'):
        while len(line) > 120:
            cut = line.rfind(', ', 0, 118) + 1
            if cut <= 4:
                break
            wrapped.append(line[:cut])
            line = '    ' + line[cut + 1:]
        wrapped.append(line)
    open(OUT, 'w').write('\n'.join(wrapped))
    print(f'{OUT}: {len(views)} views, {total} outline points, {os.path.getsize(OUT)} bytes')


if __name__ == '__main__':
    main()
